### ISSUE TITLE
NSJSONSerialization is only available for iOS 5.0 and up

### ISSUE THREAD

**Issue by megastep** [BlueParabola/Beeblex-SDK#2]
BBXIAPTransaction relies on the NSJSONSerialization system class, and in turns this makes this SDK unusable with iOS earlier than 5.

This could easily be worked around by relying on some other library, such as the SBJSON library used by the Facebook SDK. This way we can still support users who are on older devices that can't get to 5.0 (or still haven't).

**Comment by megastep** [comment]
I've fixed this and other issues in my fork of the library.

JSONKit is a simple alternative that should work for what you need, and also  [NSURLConnection sendAsynchronousRequest:queue:completionHandler:] is a new method that is not available before iOS 5.

Still needs some testing to make sure it works properly but at least it compiles and runs on iOS 4 devices for now.

**Comment by mtabini** [comment]
Thanks—I will look into these over the weekend. TBH, I'm on the fences on iOS 4 support—not enough devices out there that still run it vs. the cost of testing it.

**Comment by mtabini** [comment]
To be clear, 5.0 was our target. Maybe 4.x support belongs in a unofficial fork.

**Comment by megastep** [comment]
I realized that after taking a closer look at your FAQ, however for this kind of service you're not doing anything that really does require 5.0. All of the APIs you use have workable alternatives, and app developers like myself that still have a lot of lazy users on 4.x are reluctant to drop them just to be able to use a small library...

**Comment by mtabini** [comment]
On 2012-07-20, at 6:01 PM, Stephane Peter reply@reply.github.com wrote:

> I realized that after taking a closer look at your FAQ, however for this kind of service you're not doing anything that really does require 5.0. All of the APIs you use have workable alternatives, and app developers like myself that still have a lot of lazy users on 4.x are reluctant to drop them just to be able to use a small library...

Right, I understand, but I am reluctant to add more code for folks who don't need SBJSON, and we don't have the bandwidth to test the code and then support the service. It's a tough call.

**Comment by megastep** [comment]
In theory, this should be practically identical to your iOS 5 code in terms of what gets exchanged with your servers. I'll do some more testing later today to try to work out any kinks. So if all goes well all of the work for this would be on maintaining the client library.

FYI, the JSON library I ended up using is more lightweight than SBJSON and fairly self-contained. It also avoids further conflicts, like for apps that use the Facebook iOS SDK that also includes a copy of SBJSON.

I understand if you end up not wanting to do it, and maybe my fork can provide this for the time being. Still, look at the other patches I have for you, particularly that Reachability one that made me look at your code closely when I was trying out the library. :)

**Comment by mtabini** [comment]
> I understand if you end up not wanting to do it, and maybe my fork can provide this for the time being. Still, look at the other patches I have for you, particularly that Reachability one that made me look at your code closely when I was trying out the library. :)

Will do; what I was thinking was to define the iOS4 stuff and provided it as unsupported. Thanks for the Reachability stuff—I actually had that tested, but we must have reverted one commit too many at some point and we need better unit tests. I will give it a test and the commit it back into the tree for beta 2, which we'll put out at some point next week.

**Comment by mtabini** [comment]
I've merged your pull request in, with the new JSON library. In the end, it seems that supporting 4.x is something more people want, so we'll give it a try. Thanks!
